version: '3.8.0'

services:
  comets_backend:
    container_name: comets_backend
    build:
      context: ./backend/
    env_file:
      - ./backend/.env
    restart: always
    ports:
      - 3014:3000
  mongo:
    image: mongo
    restart: always
    container_name: "mongo"
    volumes:
      - './dockervolume/mongodb:/data/db'
  redis:
    image: 'redis:latest'
  cometspy:
    container_name: comets-flask
    build:
      context: ./comets-api/
    restart: always
    ports:
      - 5007:5000
    env_file:
      - ./comets-api/.env
  frontend:
    container_name: comets-frontend
    build:
      context: ./frontend/
    ports:
      - 3015:80
    env_file:
      - ./frontend/.env
