version: '3.8.0'

services:
  comets_backend:
    container_name: comets_backend
    build:
      context:  ../backend
      dockerfile: Dockerfile
    ports:
      - 3014:3000
  mongo:
    image: mongo
    restart: always
    container_name: "mongo"
    volumes:
      - './dockervolume/mongodb:/data/db'
  redis:
    image: 'redis:latest'
  cometspy:
    container_name: comets-flask
    build:
      context: ../comets-api
    restart: always
    ports:
      - 5007:5000
    env_file:
      - ../comets-api/.env

