version: '3.8.0'

services:
  comets_backend:
    container_name: comets_backend
    image: hicsail/comets-backend:latest
    ports:
      - 3014:3000
    env_file:
      - local.env
  mongo:
    image: mongo
    container_name: "mongo"
    volumes:
      - './dockervolume/mongodb:/data/db'
  redis:
    image: 'redis:latest'
  cometspy:
    image: hicsail/comets-flask:latest
    container_name: comets-flask
    ports:
      - 5007:5000
    env_file:
      - local.env
      - bucket.env
  frontend:
    container_name: comets-frontend
    image: hicsail/comets-frontend:local
    ports:
      - 3015:80
